### ISSUE TITLE
running on mac

### ISSUE THREAD

**Issue by air237** [petusa/CordovaServer#1]
$ cordova-server
Found Cordova project config file.
Serving "XXX" at http://localhost:8080
Processing plugin: org.apache.cordova.device
Processing plugin: org.apache.cordova.device/tests
Processing plugin: org.apache.cordova.file
Processing plugin: org.apache.cordova.file/tests
Processing plugin: org.apache.cordova.inappbrowser
Processing plugin: org.apache.cordova.inappbrowser/tests
Processing plugin: org.apache.cordova.media
Processing plugin: org.apache.cordova.media/tests
Processing plugin: org.apache.cordova.media-capture
Processing plugin: org.apache.cordova.media-capture/tests
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/cordova-server/index.js:122:17
    at Parser.<anonymous> (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/lib/xml2js.js:425:18)
    at Parser.emit (events.js:107:17)
    at Object.onclosetag (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/lib/xml2js.js:394:26)
    at emit (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/lib/xml2js.js:444:31)
    at Parser.parseString (/usr/local/lib/node_modules/cordova-server/node_modules/xml2js/lib/xml2js.js:6:61)

**Comment by petusa** [comment]
This issue is fixed now in 0.0.3 version.

jsModules gets checked, and if does NOT exist then there is no plugin XML processing (index.js file)
